version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: rootpg
      POSTGRES_PASSWORD: "123456"  # Quoted to avoid shell interpretation
      POSTGRES_DB: appdbasset_management
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rootpg"]  # Fixed: Use correct username
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy  # Wait for postgres to be healthy
    networks:
      - app-net     
    restart: unless-stopped

volumes:
  pg-data:  # Removed unused postgres_data volume

networks:
  app-net:
    driver: bridge