-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- ADDED: Create the sequence needed for the assets table's ID column.
CREATE SEQUENCE IF NOT EXISTS public.asset_seq
  INCREMENT 1
  START 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1;


CREATE TABLE IF NOT EXISTS public.asset_borrowing
(
  id character varying(255) COLLATE pg_catalog."default" NOT NULL,
  asset_tag character varying(255) COLLATE pg_catalog."default" NOT NULL,
  checkout_date date NOT NULL,
  due_date date,
  checkin_date date,
  status character varying(50) COLLATE pg_catalog."default",
  purpose character varying(255) COLLATE pg_catalog."default",
  notes text COLLATE pg_catalog."default",
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  borrowername text COLLATE pg_catalog."default",
  borrowercontact text COLLATE pg_catalog."default",
  condition character varying(50) COLLATE pg_catalog."default",
  damage_reported boolean DEFAULT false,
  damage_description text COLLATE pg_catalog."default",
  maintenance_required boolean DEFAULT false,
  maintenance_notes text COLLATE pg_catalog."default",
  returned_by_name character varying(255) COLLATE pg_catalog."default",
  CONSTRAINT asset_borrowing_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset_patch_history
(
  id character varying(255) COLLATE pg_catalog."default" NOT NULL,
  "patchId" character varying(255) COLLATE pg_catalog."default" NOT NULL,
  "patchName" character varying(255) COLLATE pg_catalog."default" NOT NULL,
  version character varying(255) COLLATE pg_catalog."default",
  description text COLLATE pg_catalog."default",
  "patchType" character varying(20) COLLATE pg_catalog."default" NOT NULL,
  severity character varying(20) COLLATE pg_catalog."default" NOT NULL,
  status character varying(20) COLLATE pg_catalog."default" NOT NULL,
  "installDate" timestamp without time zone,
  "scheduledDate" timestamp without time zone,
  size character varying(50) COLLATE pg_catalog."default",
  "kbNumber" character varying(50) COLLATE pg_catalog."default",
  "cveIds" text COLLATE pg_catalog."default",
  notes text COLLATE pg_catalog."default",
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_patch_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset_patches
(
  id character varying(255) COLLATE pg_catalog."default" NOT NULL,
  asset_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
  patch_status character varying(50) COLLATE pg_catalog."default",
  lastpatch_check date,
  operating_system character varying(255) COLLATE pg_catalog."default",
  vulnerabilities integer,
  pending_updates integer,
  critical_updates integer,
  security_updates integer,
  notes text COLLATE pg_catalog."default",
  next_checkdate date,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT asset_patches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.assets
(
  id character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT ('HW'::text || lpad((nextval('asset_seq'::regclass))::text, 5, '0'::text)),
  asset_tag character varying(255) COLLATE pg_catalog."default" NOT NULL,
  type character varying(255) COLLATE pg_catalog."default",
  manufacturer character varying(255) COLLATE pg_catalog."default",
  model character varying(255) COLLATE pg_catalog."default",
  serialnumber character varying(255) COLLATE pg_catalog."default" NOT NULL,
  purchasedate date,
  purchaseprice numeric(10, 2),
  supplier character varying(255) COLLATE pg_catalog."default",
  warrantyexpiry date,
  assigneduser character varying(255) COLLATE pg_catalog."default",
  location character varying(255) COLLATE pg_catalog."default",
  department character varying(255) COLLATE pg_catalog."default",
  status character varying(50) COLLATE pg_catalog."default",
  operatingsystem character varying(255) COLLATE pg_catalog."default",
  processor character varying(255) COLLATE pg_catalog."default",
  memory character varying(255) COLLATE pg_catalog."default",
  storage character varying(255) COLLATE pg_catalog."default",
  hostname character varying(255) COLLATE pg_catalog."default",
  ipaddress character varying(255) COLLATE pg_catalog."default",
  macaddress character varying(255) COLLATE pg_catalog."default",
  patchstatus character varying(255) COLLATE pg_catalog."default",
  lastpatch_check date,
  isloanable boolean,
  condition character varying(255) COLLATE pg_catalog."default",
  description text COLLATE pg_catalog."default",
  notes text COLLATE pg_catalog."default",
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  delete_at timestamp without time zone,
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT "assets_assetTag_key" UNIQUE (asset_tag),
  CONSTRAINT assets_asset_tag_unique UNIQUE (asset_tag),
  CONSTRAINT "assets_serialNumber_key" UNIQUE (serialnumber)
);

COMMENT ON COLUMN public.assets.delete_at
  IS 'tempDel';

CREATE TABLE IF NOT EXISTS public.inventory_items
(
 id serial NOT NULL,
  barcode character varying(255) COLLATE pg_catalog."default",
  name character varying(255) COLLATE pg_catalog."default" NOT NULL,
  description text COLLATE pg_catalog."default",
  quantity integer NOT NULL DEFAULT 0,
  min_stock_level integer NOT NULL DEFAULT 5,
  price_per_unit numeric(10, 2) DEFAULT 0.00,
  location character varying(255) COLLATE pg_catalog."default",
  category character varying(255) COLLATE pg_catalog."default",
  image_url character varying(255) COLLATE pg_catalog."default",
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_barcode_key UNIQUE (barcode)
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions
(
  id serial NOT NULL,
  item_id integer NOT NULL,
  user_id character varying(255) COLLATE pg_catalog."default",
  transaction_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
  quantity_change integer NOT NULL,
  notes text COLLATE pg_catalog."default",
  transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.software
(
  id character varying(255) COLLATE pg_catalog."default" NOT NULL,
  software_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
  publisher character varying(255) COLLATE pg_catalog."default",
  version character varying(255) COLLATE pg_catalog."default",
  license_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
  licenses_type character varying(255) COLLATE pg_catalog."default",
  purchasedate date,
  expirydate date,
  licenses_total integer,
  licenses_assigned integer,
  category character varying(255) COLLATE pg_catalog."default",
  description text COLLATE pg_catalog."default",
  notes text COLLATE pg_catalog."default",
  status character varying(50) COLLATE pg_catalog."default",
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT software_pkey PRIMARY KEY (id),
  CONSTRAINT "software_licenseKey_key" UNIQUE (license_key)
);

CREATE TABLE IF NOT EXISTS public.users
(
  id character varying(50) COLLATE pg_catalog."default" NOT NULL,
  firstname character varying(255) COLLATE pg_catalog."default",
  lastname character varying(255) COLLATE pg_catalog."default",
  email character varying(255) COLLATE pg_catalog."default" NOT NULL,
  phone character varying(255) COLLATE pg_catalog."default",
  department character varying(255) COLLATE pg_catalog."default",
  role character varying(255) COLLATE pg_catalog."default",
  location character varying(255) COLLATE pg_catalog."default",
  employee_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
  start_date date,
  status character varying(50) COLLATE pg_catalog."default",
  assets_count integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  password character varying(255) COLLATE pg_catalog."default",
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT "users_employeeId_key" UNIQUE (employee_id)
);

ALTER TABLE IF EXISTS public.asset_borrowing
  ADD CONSTRAINT asset_borrowing_asset_tag_fkey FOREIGN KEY (asset_tag)
  REFERENCES public.assets (asset_tag) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.asset_patch_history
  ADD CONSTRAINT fk_patch FOREIGN KEY ("patchId")
  REFERENCES public.asset_patches (id) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_aph_patchid
  ON public.asset_patch_history("patchId");


ALTER TABLE IF EXISTS public.asset_patches
  ADD CONSTRAINT "asset_patches_assetId_fkey" FOREIGN KEY (asset_id)
  REFERENCES public.assets (id) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.assets
  ADD CONSTRAINT assets_assigned_employee_id_fkey FOREIGN KEY (assigneduser)
  REFERENCES public.users (employee_id) MATCH SIMPLE
  ON UPDATE CASCADE
  ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_transactions
  ADD CONSTRAINT inventory_transactions_item_id_fkey FOREIGN KEY (item_id)
  REFERENCES public.inventory_items (id) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_item_id
  ON public.inventory_transactions(item_id);


ALTER TABLE IF EXISTS public.inventory_transactions
  ADD CONSTRAINT inventory_transactions_user_id_fkey FOREIGN KEY (user_id)
  REFERENCES public.users (id) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

END;